

export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

export const AZURE_CONNECTION_STRING = process.env.AZURE_CONNECTION_STRING;